//generated by https://start.spring.io/
package com.blueteam.timekeeping;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;

@SpringBootApplication
public class TimekeepingApplication {

	public static void main(String[] args) {
		
		SpringApplication.run(TimekeepingApplication.class, args);	
	}

}
